import { LucideUsers as Users, LucideActivity as Activity, LucideAlertTriangle as AlertTriangle, LucideUserPlus as UserPlus, LucideLayoutDashboard as LayoutDashboard, LucideFileText as FileText, LucideSettings as Settings, LucideMenu as Menu, LucideMoon as Moon, LucideSun as Sun, LucideHome as Home, LucideChevronRight as ChevronRight, LucideBriefcase as Briefcase, LucideCalculator as Calculator, LucideX as X, LucideMonitor as Monitor, LucideLogOut as LogOut, LucideCheckCircle as CheckCircle, LucideClock as Clock, LucideDollarSign as DollarSign, LucideTrendingDown as TrendingDown, LucidePieChart as PieChart, LucideLock as Lock, LucideShield as Shield, LucideBuilding2 as Building2, LucidePackage as Package, LucideFileDown as FileDown, LucideGitMerge as GitMerge, LucideChartColumn as ChartColumn, LucideUserCheck as UserCheck, LucideUserX as UserX, LucideKey as Key, LucideFileUp as FileUp, LucideDownload as Download, LucideReceipt as Receipt, LucideEye as Eye, LucideBot as Bot, LucideUser as User, LucideSend as Send, LucideAlertCircle as AlertCircle, LucideRefreshCw as RefreshCw, LucidePlus as Plus, LucideSearch as Search, LucideMessageSquare as MessageSquare, LucideCheck as Check, LucideEdit2 as Edit2, LucideTrash2 as Trash2 } from '@lucide/angular';

export const APP_LUCIDE_ICONS = {
  'users': Users,
  'activity': Activity,
  'alert-triangle': AlertTriangle,
  'user-plus': UserPlus,
  'layout-dashboard': LayoutDashboard,
  'file-text': FileText,
  'settings': Settings,
  'menu': Menu,
  'moon': Moon,
  'sun': Sun,
  'home': Home,
  'chevron-right': ChevronRight,
  'briefcase': Briefcase,
  'calculator': Calculator,
  'x': X,
  'monitor': Monitor,
  'log-out': LogOut,
  'check-circle': CheckCircle,
  'clock': Clock,
  'dollar-sign': DollarSign,
  'trending-down': TrendingDown,
  'pie-chart': PieChart,
  'lock': Lock,
  'shield': Shield,
  'building-2': Building2,
  'package': Package,
  'file-down': FileDown,
  'git-merge': GitMerge,
  'chart-column': ChartColumn,
  'user-check': UserCheck,
  'user-x': UserX,
  'key': Key,
  'file-up': FileUp,
  'download': Download,
  'receipt': Receipt,
  'eye': Eye,
  'bot': Bot,
  'user': User,
  'send': Send,
  'alert-circle': AlertCircle,
  'refresh-cw': RefreshCw,
  'plus': Plus,
  'search': Search,
  'message-square': MessageSquare,
  'check': Check,
  'edit-2': Edit2,
  'trash-2': Trash2
};

export type AppIcon = keyof typeof APP_LUCIDE_ICONS;

export const APP_LUCIDE_ICONS_ARRAY = [
  Users,
  Activity,
  AlertTriangle,
  UserPlus,
  LayoutDashboard,
  FileText,
  Settings,
  Menu,
  Moon,
  Sun,
  Home,
  ChevronRight,
  Briefcase,
  Calculator,
  X,
  Monitor,
  LogOut,
  CheckCircle,
  Clock,
  DollarSign,
  TrendingDown,
  PieChart,
  Lock,
  Shield,
  Building2,
  Package,
  FileDown,
  GitMerge,
  ChartColumn,
  UserCheck,
  UserX,
  Key,
  FileUp,
  Download,
  Receipt,
  Eye,
  Bot,
  User,
  Send,
  AlertCircle,
  RefreshCw,
  Plus,
  Search,
  MessageSquare,
  Check,
  Edit2,
  Trash2
];
